---
- hosts: "masters,workers"
  gather_facts: yes
  vars:
   - k8s_version: 1.19.1-00
  tasks:
     - name: update and install docker & other required packages 
       shell: |
               sudo apt-get update
               sudo apt-get install docker.io -y 
               sudo apt-get update && apt-get install -y apt-transport-https curl

     - name: Download and add key, Add K8s Source
       shell: |
               sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
               sudo echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" >/etc/apt/sources.list.d/kubernetes.list

     - name: install kubernetes components with version (kubeadm, kubectl, kubelet)
       shell: |
               sudo apt-get update
               sudo apt install -y kubeadm="{{k8s_version}}" kubectl="{{k8s_version}}" kubelet="{{k8s_version}}"

     - name: check kubernetes components version
       shell: |
               sudo kubectl version --client
               sudo kubeadm version