- hosts: workers
  become: yes
  gather_facts: yes

  tasks:
   - name: Copy join command from Ansiblehost to the worker nodes.
     copy:
       src: /tmp/kubernetes_join_command
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: reset kubeadm
     shell: sudo kubeadm reset

   - name: Join the Worker nodes to the cluster.
     become: yes
     command: sudo sh /tmp/kubernetes_join_command
     register: joined_or_not